# Use the official Maven image as the base image
FROM maven:3.8.4-openjdk-17-slim AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY pom.xml .
COPY src ./src

# Build the application
RUN mvn clean package

# Use the official OpenJDK image as the base image for the final image
FROM openjdk:17

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the build stage to the current stage
COPY --from=build /app/target/ssp_backend-3.2.1.jar ./app.jar

# Expose the port your Spring Boot application will run on
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]