version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  ssp_backend:
    image: ssp_backend:latest
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  ssp_frontend:
    image: ssp_frontend:latest
    depends_on:
      - ssp_backend
    restart: always
    ports:
      - "4200:4200"
    environment:
      API_URL: http://spring-boot-app:8080/api
